import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './ui/globals.css'
import Navbar from './ui/navbar/navbar'
import SideBar from './ui/sidebar/sidebar'
import styles from './ui/layout.module.css'
const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Salvaterra Fight Club',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className={styles.container}>
          <div className={styles.menu}>
            <SideBar />
          </div>
          <div className={styles.content}>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
